# Generated by Django 4.2.16 on 2024-12-16 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN_No', models.CharField(max_length=100, unique=True)),
                ('Book_Name', models.CharField(max_length=100)),
                ('Author_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book_issued',
            fields=[
                ('Book_issued_id', models.AutoField(primary_key=True, serialize=False)),
                ('Issued_Date', models.DateField(default=datetime.date.today)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
