# Generated by Django 4.2.16 on 2024-12-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_issued',
            name='Book_Name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='staff.add_book'),
        ),
    ]
