# Generated by Django 4.2.16 on 2024-11-20 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_remove_register_master_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_master',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='profile_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='images/')),
                ('upload_doc', models.FileField(upload_to='Document/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.register_master')),
            ],
        ),
    ]
