# Generated by Django 4.2.16 on 2024-12-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.CharField(max_length=20)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.chapter')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.question')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subject')),
            ],
        ),
    ]
